add change liquidity entrypoint
invariant-labs/protocol-azero pull request #296
Opened 2024-09-11 14:05 UTC by none00y

# Changes
- add change liquidity entrypoint

2024-09-11 16:32 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    fn change_liquidity(
entrypoint doc seems outdated

2024-09-12 11:34 UTC, wojciech-cichocki requested changes

2024-09-12 11:34 UTC, wojciech-cichocki commented on src/e2e/change_liquidity.rs
> +    async fn test_change_liquidity_no_position(mut client: ink_e2e::Client<C, E>) -> E2EResult<()> {
Is there a test for insufficient tokens to cover the liquidity change in the position?

2024-09-12 11:34 UTC, wojciech-cichocki commented on sdk/src/invariant.ts
> +    newLiquidity: Liquidity,
`deltaLiquidity` and `depositDirection = DEPOSIT | WITHDRAW` suit better IMO

2024-09-13 12:29 UTC, zielvna approved these changes

2024-09-17 09:47 UTC, wojciech-cichocki approved these changes

2024-09-17 10:16 UTC, merged