Random swap script for testnet
invariant-labs/protocol-azero pull request #309
Opened 2024-10-11 13:43 UTC by DevRozaDev

2024-10-14 16:10 UTC, zielvna requested changes

2024-10-14 16:10 UTC, zielvna commented on scripts/package.json
> +    "random-swap-testnet": "npx tsc && node --experimental-wasm-modules target/random-swap-testnet.js"
i guess this script was in `scripts` directory before and that's a leftover?

2024-10-14 16:10 UTC, zielvna commented on cron/.env
> +NEW_DEPLOYER_MNEMONIC=
`RECEIVER_ADDRESS` and `NEW_DEPLOYER_MNEMONIC` are not used in this script

2024-10-14 16:10 UTC, zielvna commented on cron/src/random-swap-testnet.ts
> +  api.tx.utility.batch
i think this line can be deleted

2024-10-15 02:47 UTC, wojciech-cichocki requested changes
Please add small `README.md` file here

2024-10-15 02:50 UTC, wojciech-cichocki requested changes

2024-10-15 02:50 UTC, wojciech-cichocki commented on cron/src/random-swap-testnet.ts
> +        : simulation.amountOut * BigInt(Math.trunc(multiplier * 100000))) / 100000n
why?

2024-10-15 10:59 UTC, wojciech-cichocki approved these changes

2024-10-15 11:06 UTC, zielvna commented on cron/README.md
> +DEPLOYER_MNEMONIC=add your mnemonic here this is the right place for twelve words
it looks like it was change to `USER_MNEMONIC`

2024-10-15 11:07 UTC, zielvna approved these changes

2024-10-15 11:18 UTC, merged